### ISSUE TITLE
Zabbix Data Sources integration

### ISSUE THREAD

**Issue by Diwahars** [grafana/grafana-plugins#20]
Hi,

How to add configure zabbix in grafana using zabbix datasource?

i couldn't find config.js??

could you please help me in this?

**Comment by torkelo** [comment]
Zabbix does not seem to be updated to support Grafana 2.x yet

**Comment by Diwahars** [comment]
thanks @torkelo 

How to run grafana 1.9??

**Comment by torkelo** [comment]
@Diwahars there are download and docs for Grafana 1.0 http://grafana.org/download/

But no docs for how to get Zabbix data source configured and working,

**Comment by alexanderzobnin** [comment]
@torkelo Please, merge pull request #19 - I added installation instructions.
@Diwahars, you may see also my [grafana-zabbix](https://github.com/alexanderzobnin/grafana-zabbix) repo with latest updates and improvements. There's installation instructions.

**Comment by torkelo** [comment]
@alexanderzobnin merged

**Comment by alexanderzobnin** [comment]
@torkelo Thanks!
