### ISSUE TITLE
KairosDB Grafana 2.0

### ISSUE THREAD

**Issue by arussellsaw** [grafana/grafana-plugins#28]
are there any plans to update the KairosDB plugin for Grafana 2.0? this is our main blocker for updating to 2.0 and i'd love to know a timescale on when i can start to look at upgrading.

thanks

**Comment by alexanderzobnin** [comment]
See grafana sources ([datasource](https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource) directory). It seems, KairosDB now supported "out-of-box".

**Comment by torkelo** [comment]
KairosDB is supported out of the box in the Grafana 2.1 pre release builds, http://grafana.org/download/builds.html
