### ISSUE TITLE
Druid Plugin with 2.5 Grafana

### ISSUE THREAD

**Issue by abhisant** [grafana/grafana-plugins#56]
I am trying to integrate the following druid plugin to Grafana 2.5, I tried to fix few dependencies in plugin.json and datasource.js, but when I try to add the query for generating graphs, it't not rendering the partials/query.editor.html. The same thing works in 2.1.3. Could you please help me out. Thank you in advance.

**Comment by alexanderzobnin** [comment]
@abhisant see more info about breaking changes un Grafana 2.5 here:
https://github.com/grafana/grafana/blob/master/docs/sources/datasources/plugin_api.md
https://github.com/grafana/grafana/blob/master/public/app/plugins/PLUGIN_CHANGES.md

**Comment by abhisant** [comment]
Thanks for the quick response.

**Comment by alexanderzobnin** [comment]
If it help you, see changes what I made for fix my plugin
https://github.com/alexanderzobnin/grafana-zabbix/commit/1cfb8ddceb5f3a79e813170e2253f53601c65a96

**Comment by abhisant** [comment]
Yes, I was able to fix the issue and able to render query.editor.html by the documentation link. Thanks a lot for inputs. Currently I am working on fixing the query.editor.html. Thanks again.
